---
name: Personal Build and Push
on:
  push:
    branches:
      - "main"
      - "feature/**"
      - "feature-wip/**"
      - "fix/**"
      - "fix-wip/**"
  pull_request:

jobs:
  build_n_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - run: echo '{}' > .local-config.json

      - name: Build
        run: npm run build
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/netbird-dashboard
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Delete untagged GHCR images after push
        if: github.event_name != 'pull_request'
        uses: Chizkiyahu/delete-untagged-ghcr-action@v6
        continue-on-error: true
        with:
          token: ${{ secrets.PAT_GHCR_DELETE_IMAGES }}
          untagged_only: true
          except_untagged_multiplatform: true
          with_sigs: true
          owner_type: 'user'

